services:
  - type: web
    name: f1-xgboost-api
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 127.0.0.1 --port 8000
